"""Regenerate the embedded TC-CS-004 fixture using pydicom==3.0.2.

Run from the project root with pydicom installed. No patient data is used.
The tiny synthetic CT series exercises upload verification, not clinical quality.
"""
import base64
import io
from pathlib import Path
import struct
import zipfile

from pydicom import dcmread, dcmwrite
from pydicom.dataset import FileDataset, FileMetaDataset
from pydicom.uid import CTImageStorage, ExplicitVRLittleEndian

archive_buffer = io.BytesIO()
with zipfile.ZipFile(archive_buffer, "w", zipfile.ZIP_DEFLATED) as archive:
    for index in range(1, 5):
        instance_uid = f"2.25.304004.{index}"
        meta = FileMetaDataset()
        meta.MediaStorageSOPClassUID = CTImageStorage
        meta.MediaStorageSOPInstanceUID = instance_uid
        meta.TransferSyntaxUID = ExplicitVRLittleEndian
        meta.ImplementationClassUID = "2.25.304004.99"
        dataset = FileDataset(None, {}, file_meta=meta, preamble=b"\0" * 128)
        dataset.SOPClassUID = CTImageStorage
        dataset.SOPInstanceUID = instance_uid
        dataset.StudyInstanceUID = "2.25.304004.100"
        dataset.SeriesInstanceUID = "2.25.304004.200"
        dataset.FrameOfReferenceUID = "2.25.304004.300"
        dataset.PatientName = "SYNTHETIC^UAT"
        dataset.PatientID = "TC-CS-004"
        dataset.PatientBirthDate = ""
        dataset.PatientSex = "O"
        dataset.StudyDate = "20260101"
        dataset.StudyTime = "120000"
        dataset.AcquisitionDate = "20260101"
        dataset.ContentDate = "20260101"
        dataset.ContentTime = "120000"
        dataset.AccessionNumber = ""
        dataset.ReferringPhysicianName = ""
        dataset.StudyID = "UAT004"
        dataset.SeriesNumber = 1
        dataset.InstanceNumber = index
        dataset.Modality = "CT"
        dataset.ImageType = ["DERIVED", "SECONDARY", "AXIAL"]
        dataset.SeriesDescription = "SYNTHETIC UAT - NOT FOR CLINICAL USE"
        dataset.Manufacturer = "UAT FIXTURE"
        dataset.PatientPosition = "HFS"
        dataset.PositionReferenceIndicator = ""
        dataset.SliceThickness = "1"
        dataset.SpacingBetweenSlices = "1"
        dataset.ImagePositionPatient = [0, 0, index - 1]
        dataset.ImageOrientationPatient = [1, 0, 0, 0, 1, 0]
        dataset.PixelSpacing = [1, 1]
        dataset.Rows = 8
        dataset.Columns = 8
        dataset.SamplesPerPixel = 1
        dataset.PhotometricInterpretation = "MONOCHROME2"
        dataset.BitsAllocated = 16
        dataset.BitsStored = 16
        dataset.HighBit = 15
        dataset.PixelRepresentation = 1
        dataset.RescaleIntercept = "0"
        dataset.RescaleSlope = "1"
        dataset.RescaleType = "HU"
        dataset.PixelData = struct.pack("<64h", *[index * 10 + n for n in range(64)])
        dicom_buffer = io.BytesIO()
        dcmwrite(dicom_buffer, dataset, enforce_file_format=True)
        dicom_buffer.seek(0)
        verified = dcmread(dicom_buffer)
        assert verified.Modality == "CT" and len(verified.PixelData) == 128
        entry = zipfile.ZipInfo(f"slice-{index:03d}.dcm", (2026, 1, 1, 0, 0, 0))
        entry.compress_type = zipfile.ZIP_DEFLATED
        archive.writestr(entry, dicom_buffer.getvalue())

encoded = base64.b64encode(archive_buffer.getvalue()).decode("ascii")
target = Path(__file__).resolve().parents[1] / "tests/helpers/synthetic-ct.ts"
target.write_text(
    "// Generated by scripts/generate-synthetic-ct.py using pydicom 3.0.2.\n"
    "// Four 8x8 synthetic CT slices. No patient data; not for clinical use.\n"
    "// Embedded to avoid missing binary fixtures on local machines and CI.\n"
    "export const syntheticCtRoundTwo = {\n"
    "  name: 'tc-cs-004-round-2-ct.zip',\n"
    "  mimeType: 'application/zip',\n"
    f"  buffer: Buffer.from('{encoded}', 'base64'),\n"
    "};\n",
    encoding="utf-8",
)
print(f"Generated and validated 4 synthetic CT slices: {target.name}")
